// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApFuuIhLE0ixdiXJrx18eNwX301hfo9jI',
    appId: '1:103005672908:web:b95238193531912490f969',
    messagingSenderId: '103005672908',
    projectId: 'ecommerceapp-be668',
    authDomain: 'ecommerceapp-be668.firebaseapp.com',
    storageBucket: 'ecommerceapp-be668.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtHABilXW05KN9zmi7Z8mRodL_V435mVA',
    appId: '1:103005672908:android:7a2505de7eefe3bf90f969',
    messagingSenderId: '103005672908',
    projectId: 'ecommerceapp-be668',
    storageBucket: 'ecommerceapp-be668.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEZIj1LqWsCoj9TbpzzGX7zkJHVqYMOfE',
    appId: '1:103005672908:ios:61ff76adfd90fec590f969',
    messagingSenderId: '103005672908',
    projectId: 'ecommerceapp-be668',
    storageBucket: 'ecommerceapp-be668.appspot.com',
    iosBundleId: 'com.example.myproject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEZIj1LqWsCoj9TbpzzGX7zkJHVqYMOfE',
    appId: '1:103005672908:ios:61ff76adfd90fec590f969',
    messagingSenderId: '103005672908',
    projectId: 'ecommerceapp-be668',
    storageBucket: 'ecommerceapp-be668.appspot.com',
    iosBundleId: 'com.example.myproject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApFuuIhLE0ixdiXJrx18eNwX301hfo9jI',
    appId: '1:103005672908:web:825e8e36e83aeb1c90f969',
    messagingSenderId: '103005672908',
    projectId: 'ecommerceapp-be668',
    authDomain: 'ecommerceapp-be668.firebaseapp.com',
    storageBucket: 'ecommerceapp-be668.appspot.com',
  );
}
